---
abstract: 'forms a complete PSGI application from various middlewares'
author:
  - 'Takatoshi Kitano <kitano.tk@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Plack: 0
  Test::LoadAllModules: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlackX-MiddlewareStack
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Tie::LLHash: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.011
